web: gunicorn TemplateRoot:app

worker: gunicorn UpdateCompanyProfile.py
worker: gunicorn sqlwrapper.py
worker: gunicorn UpdateProfileRecord.py
worker: gunicorn UpdateProfilePreference.py
worker: gunicorn UpdateProfileNotes.py
worker: gunicorn UpdateProfileCreditcard.py
worker: gunicorn UpdateNegotiatedRate.py
worker: gunicorn UpdateIndividualProfile.py
worker: gunicorn QueryProfileRecord.py
worker: gunicorn QueryNegotiatedRate.py
worker: gunicorn DeleteProfileRecord.py
worker: gunicorn UpdateProfileCreditcardRecord.py
worker: gunicorn UpdateProfileNegotiatedRateRecord.py
worker: gunicorn UpdateProfileNotesRecord.py
worker: gunicorn UpdateProfilePreferencenew.py
worker: gunicorn QueryProfileRecordAll.py
worker: gunicorn MergeProfile.py
worker: gunicorn DeleteProfileRecordAll.py
worker: gunicorn QueryProfileHistory.py
worker: gunicorn HOTEL_RES_GET_SELECT_QueryAlertReservation.py
worker: gunicorn HOTEL_RES_GET_SELECT_QueryDepositrule.py
worker: gunicorn HOTEL_RES_GET_SELECT_QueryFixedChargesReservation.py
worker: gunicorn Hotel_RES_Get_Select_QueryReservationActivitylog.py
worker: gunicorn HOTEL_RES_GET_SELECT_QueryWaitlistReservation.py
worker: gunicorn HOTEL_RES_GET_SELECT_RoomUnassign.py
worker: gunicorn HOTEL_RES_POST_INSERT_UpdateAlertReservation.py
worker: gunicorn HOTEL_RES_POST_INSERT_UpdateDeposit.py
worker: gunicorn Hotel_RES_Post_Insert_UpdateFixedChargesReservation.py
worker: gunicorn HOTEL_RES_POST_INSERT_UpdateFixedRateReservation.py
worker: gunicorn Hotel_RES_Post_Insert_UpdateGuestPrivileges.py
worker: gunicorn Hotel_RES_Post_Insert_UpdateGuestTraces.py
worker: gunicorn HOTEL_RES_POST_INSERT_UpdateNewReservation.py
worker: gunicorn HOTEL_RES_POST_INSERT_WaitlistReservation.py
worker: gunicorn HOTEL_RES_POST_UPDATE_UpdateDeposit.py
worker: gunicorn HOTEL_RES_POST_UPDATE_UpdateFixedChargesReservation.py
worker: gunicorn HOTEL_RES_POST_UPDATE_UpdateFixedRateReservation.py
worker: gunicorn HOTEL_RES_POST_UPDATE_UpdateReservation.py
worker: gunicorn HOTEL_RES_POST_UPDATE_UpdateReservationAlert.py
worker: gunicorn HOTEL_RES_POST_UPDATE_UpdateWaitlistReservation.py
worker: gunicorn Hotel_RES_Post_Select_Queryreservation.py
worker: gunicorn HOTEL_FD_POST_INSERT_UpdateQueueRreservation.py
worker: gunicorn HOTEL_FD_GET_SELECT_QueryQueueReservation.py
worker: gunicorn Hotel_RM_Post_Insert_Updateroom.py
worker: gunicorn Hotel_RM_Post_Select_Queryhousekeepinglist.py
worker: gunicorn Hotel_RM_Post_Select_Queryoutoforderservice.py
worker: gunicorn Hotel_RM_Post_Select_Queryroommaintenance.py
worker: gunicorn Hotel_RM_Post_Update_Updateroomdiscrepancies.py
worker: gunicorn Hotel_RM_Post_Update_Updateroomstatus.py
worker: gunicorn AMAZON_RESERVATION_LAMBDA_LEX.py
worker: gunicorn profilecity.py
worker: gunicorn profileinsertvalue.py
worker: gunicorn HOTEL_RES_POST_INSERT_InsertReservationValue.py
worker: gunicorn HOTEL_RES_GET_SELECT_QueryReservationValue.py
worker: gunicorn RoomManagementDropdown.py
worker: gunicorn Hotel_Rm_Post_Select_QueryRoomList.py
worker: gunicorn Hotel_Rm_Post_Select_QueryRoomCondition.py
worker: gunicorn Hotel_Rm_Post_Update_UpdateRoomCondition.py
worker: gunicorn profilesearch.py
worker: gunicorn RoomManagementDropdownInsert.py
worker: gunicorn Hotel_RES_POST_SELECT_QueryFutureReservation.py
worker: gunicorn QueryReservationSearch.py
worker: gunicorn HOTEL_RES_POST_SELECT_QueryHistoryReservation.py
worker: gunicorn HOTEL_RES_GET_SELECT_QueryFixedRateReservation.py
worker: gunicorn HOTEL_RES_POST_INSERT_CancelReservation.py
worker: gunicorn HOTEL_RES_POST_INSERT_ReinstateReservation.py
worker: gunicorn HOTEL_RES_POST_SELECT_QueryArrivalFromToReservation.py
worker: gunicorn HOTEL_RES_POST_INSERT_WaitlistReason.py
worker: gunicorn HOTEL_RES_POST_INSERT_AcceptWaitlistReservation.py
